### ISSUE TITLE
Error Check TYPE_ITEM in Func (ITEMS_GetRunesTxtRecordFromItem)

### ISSUE THREAD

**Issue by raumuongluoc** [ThePhrozenKeep/D2MOO#1]
Error:
```
if (pItem->dwUnitType != UNIT_ITEM || !pItem->pItemData || pItem->pItemData->dwQualityNo < ITEMQUAL_MAGIC || pItem->pItemData->dwQualityNo > ITEMQUAL_TEMPERED)
```
Fix:
```
if (pItem->dwUnitType == UNIT_ITEM || pItem->pItemData || pItem->pItemData->dwQualityNo < ITEMQUAL_MAGIC || pItem->pItemData->dwQualityNo > ITEMQUAL_TEMPERED)
```

**Comment by Lectem** [comment]
I just checked and this is indeed what the game does. 
It's probably some other function that did the check and got inlined, since later there is an assert that checks `pItem->dwUnitType == UNIT_ITEM`.

I rewrote the function with a comment about it, you can check the pull request.
