### ISSUE TITLE
[D2Game] Error D2GAME_MERCS_EquipItem_6FC88D10

### ISSUE THREAD

**Issue by thaison1995** [ThePhrozenKeep/D2MOO#105]
**When we use the sword in mercenaries act 3, the item will disappear because the function only checks the item on the right hand side, not on the left hand side, and so are the other entries it seems to work only in the right hand.**

**Origin:** 
```
uint8_t nTargetBodyLoc = nBodyLoc1;
if (pMerc->dwClassId == MONSTER_ACT3HIRE && ITEMS_CheckItemTypeId(pItem, ITEMTYPE_SHIELD))
{
        pExchangeItem = pTempItem;
        nTargetBodyLoc = nBodyLoc2;
}
```
**Fix:**
```
uint8_t nTargetBodyLoc = nBodyLoc1;
if (pMerc->dwClassId == MONSTER_ACT3HIRE && ITEMS_CheckItemTypeId(pItem, ITEMTYPE_SHIELD))
{
        pExchangeItem = pTempItem;
        nTargetBodyLoc = nBodyLoc2;
}
else
{
        nBodyLoc2 = nTargetBodyLoc;
}
```

**Comment by Mw95** [comment]
Unless I am missing something, this can not be the full fix because `nBodyLoc2` is not unused anymore after this block

**Comment by thaison1995** [comment]
sorry i was wrong, thanks for the reply, you can delete or close this topic
