### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by silvermane-HU** [ThePhrozenKeep/D2MOO#135]
//D2Game.0x6FCD0840
int32_t __fastcall AITTACTICS_WalkCloseToUnit(D2GameStrc* pGame, D2UnitStrc* pUnit, int32_t nMaxDistance);
//D2Game.0x6FCD0D00
int32_t __fastcall AITTACTICS_RunCloseToTargetUnit(D2GameStrc* pGame, D2UnitStrc* pUnit, D2UnitStrc* pTarget, int32_t nMaxDistance);

spelling error with double T

//D2Common.0x6FDB9C10 (#10166)
D2ActiveRoomStrc* __stdcall PATH_GetRoom(D2DynamicPathStrc* pDynamicPath);
//D2Common.0x6FDB9C10 (#11265)
int __stdcall STATLIST_GetSkillId(D2StatListStrc* pStatList);

duplicate address listed

**Comment by Mw95** [comment]
I don't think the duplicated address is an issue at all... These are very short functions with the same assembly code which the compiler just optimized into one address

**Comment by Lectem** [comment]
I can confirm that it is indeed the same address due to COMDAT folding.
