### ISSUE TITLE
padding in D2QuestDataStrc  / D2QuestGUIDStrc

### ISSUE THREAD

**Issue by silvermane-HU** [ThePhrozenKeep/D2MOO#136]
struct D2QuestDataStrc
{...
D2QuestGUIDStrc tPlayerGUIDs;			        //0x1C
uint16_t dw9E;							//0x9E 

struct D2QuestGUIDStrc						//sizeof 0x84
{
	uint32_t nPlayerGUIDs[32];				//0x00 - players that have entered the quest zone
	uint16_t nPlayerCount;					//0x80
	uint8_t pad0x82[2];						//0x82
};

If the padding of 2 bytes is in D2QuestGUIDStrc and the size 0x84, then it shouldn't also be in D2QuestData, right?

**Comment by Lectem** [comment]
Thanks, it was indeed an error. Fixed !
