### ISSUE TITLE
UNITS_GetFrameBonus & D2COMMON_11013_ConvertMode - Synchronization issues

### ISSUE THREAD

**Issue by Araksson** [ThePhrozenKeep/D2MOO#17]
//D2Common.0x6FDC0FC0 (#10436)
int __stdcall UNITS_GetFrameBonus(D2UnitStrc* pUnit)

This feature has timing issues in "hth" mode when the character dies.

Verified with Sorceress.

The head of the Sorceress goes "crazy" and does not show the proper location as she walks after dying.

Possibly it is related to an internal function, I have not verified exactly which one, although my suspicions point to this other:

//D2Common.0x6FDB30A0 (#11013)
void __stdcall D2COMMON_11013_ConvertMode(D2UnitStrc* pUnit, int* pType, int* pClass, int* pMode, char* szFile, int nLine)

**Comment by Lectem** [comment]
Closing as it was confirmed quite a while ago the issue was related to bad structure packing on your side and not the code itself. I did however rewrite the code a bit to make it easier to read.
