### ISSUE TITLE
News

### ISSUE THREAD

**Issue by Araksson** [ThePhrozenKeep/D2MOO#29]
D2Common.0x6FDB64A0 and LoadItemStatCost Now they seem to work properly, however the STATLIST_InsertStatModOrFail_6FDB7690 and D2Common.0x6FDB5830 functions are not working properly.

STATLIST_InsertStatModOrFail_6FDB7690 it's wrong in some ISC, example: Cold Skill Damage %
D2Common.0x6FDB5830 it has a problem with the Auras. The auras of nearby friendly units do not share it with other friendly units (disabling it works perfectly).

**Comment by Lectem** [comment]
Do you have more details about the Auras ?

It seems to work fine for me after patching 0x6FDB5830  by using an act2 mercenary.
![image](https://user-images.githubusercontent.com/6024225/118270438-5d7b1500-b4c0-11eb-97ac-f80e085abdef.png)

**Comment by Araksson** [comment]
I checked all the code (this time updated) and only found 2 functions not working.

```
STATLIST_InsertStatModOrFail (sub_6FDB7690) Wrong ISC With OP 2
STATLIST_SetStat (#10463) Not Load The Game
```

in the case of the last function, in Vanilla it seems to be a independent function (which doesn't just make a call and "go"), and uses pUnit.

**Comment by Lectem** [comment]
It's been a while and afaik I couldn't reproduce the issue (however it does not mean it is fixed).
Should I keep this issue open ?

**Comment by Araksson** [comment]
> It's been a while and afaik I couldn't reproduce the issue (however it does not mean it is fixed). Should I keep this issue open ?

Those issues were fixed.
