### ISSUE TITLE
Function (D2Common_STATES_ToggleState_6FDB8900) Not Working

### ISSUE THREAD

**Issue by raumuongluoc** [ThePhrozenKeep/D2MOO#35]
- i tested the function it doesnt work and you error 2 is 
`gdwBitMasks[nState % 32] -> gdwBitMasks[nState % 31]`

`bool bStateMaskDisguise = pStatesTxtRecord->dwStateFlags & gdwBitMasks[STATEMASK_DISGUISE];`
Fix
`bool bStateMaskNoSend = pStatesTxtRecord->dwStateFlags & gdwBitMasks[STATEMASK_NOSEND];`

- i fixed the code my way and it works
[Link](https://pastebin.com/gyi78wPN)

**Comment by Lectem** [comment]
From what I see from the original DLL, the code is checking `(pStatesTxtRecord + 0x12) & gdwBitMasks[0]`.
`dwStateFlags` is located at `pStatesTxtRecord + 0x10`, so it effectively checks the 16th bit ( 2Bytes = 16bits), and `STATEMASK_DISGUISE = 16`.

Did you test this ingame ? If yes, how ?

**Comment by Lectem** [comment]
I just checked ingame, and `STATEMASK_DISGUISE` is correct here. If we put `STATEMASK_NOSEND`, then the druid can not turn into a werewolf.

**Comment by Necrolis** [comment]
> gdwBitMasks[nState % 32] -> gdwBitMasks[nState % 31]
This is incorrect, its either `% 32` or, what the binary was optimized to `& 31`.

I can confirm `STATEMASK_DISGUISE ` is correct (and logically NOSEND doesn't fit here either)
