### ISSUE TITLE
[D2Game] Error PLRTRADE_HandleCubeInteraction

### ISSUE THREAD

**Issue by thaison1995** [ThePhrozenKeep/D2MOO#95]
**if (pCubeMainTxtRecord->bOp = 0)-> the variable (bOpConditionsFulfilled) is always = false.
while the function below has the condition variable (bOpConditionsFulfilled >= 1)**

**repair**
```
....
switch (pCubeMainTxtRecord->nOp)
{
     ...
     default:
       break;
}
```
**to**
```
....
switch (pCubeMainTxtRecord->nOp)
{
     ...
    default:
    {
          bOpConditionsFulfilled = true;
          break;
    }
}
```

**Comment by Lectem** [comment]
Thanks for the report!
